npm install gitbook-plugin-favicon -g
npm install gitbook-plugin-yahei -g
npm install gitbook-plugin-github -g
npm install gitbook-plugin-autotheme -g
npm install gitbook-plugin-search-plus -g
npm install gitbook-plugin-prism -g
npm install gitbook-plugin-github-buttons -g
npm install gitbook-plugin-splitter -g
npm install gitbook-plugin-sharing-plus -g
npm install gitbook-plugin-tbfed-pagefooter -g
npm install gitbook-plugin-expandable-chapters-small -g
npm install gitbook-plugin-book-summary-scroll-position-saver -g
npm install gitbook-plugin-ga -g
npm install gitbook-plugin-baidu -g
npm install gitbook-plugin-donate -g
npm install gitbook-plugin-anchors -g
npm install gitbook-plugin-anchor-navigation-ex -g
npm install gitbook-plugin-sitemap-general -g
npm install gitbook-plugin-copy-code-button -g
npm install gitbook-plugin-mygitalk -g
npm install gitbook-plugin-multipart -g
